In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction
`Deep learning` is a specialised form of deep learning that involves neural network with many deep layers. Neural networks are designed to mimic the human's brain ability to recognize patterns and intercept complex data such as iamge, sound, or text

### Difference b/w machine learning and deep learning

<ul>
    Machine learning is used for tabular or structured data
  <li>
    Machine learning requires feature engineering (select best relevant features)
  </li>
  <li>
    Simpler and easy to interpret
  </li>
  <li>
    Are computationally efficient and doesn't require high processing power
  </li>
</ul>

<ul>
    Deep learning works better for unstructured data like images, text, sound or video
  <li>
    Doesn't requires feature engineering
  </li>
  <li>
    Due to complexity and depth, they are difficult to understand and are referred as black box
  </li>
  <li>
    Works better with large amount of training data
  </li>
  <li>
    Requires substantional competitive power
  </li>
</ul>

### Neural Network
They are complex computational models that are inspired by human brain strucutre and function. It consist of following layers
<ul>
  <li>
    Artifical neurons or nodes
  </li>
  <li>
    Input layer
  </li>
  <li>
    One or more hidden layers
  </li>
  <li>
    Output layer
  </li>
</ul>

`Neurons` are fundamental units of neural network which
<ul>
  <li>
    Recieves an input
  </li>
  <li>
    Process the input
  </li>
  <li>
    Produces an output
  </li>
</ul>

Each neuron has its own linear regresion model that is used to predict output using weighted inputs

Each neuron has an activation function that introduces non-linear into the network, enabling it to learn and model complex problems. An `activation function` decides whether a neuron should be activated or not. This means that `it will decide whether the neuron's input to the network is important or not in the process of prediction using simpler mathematical operations.`
<ul>
  <li>
    Sigmoid (outputs between 0 and 1)
  </li>
  <li>
    Tanh (output between -1 and 1)
  </li>
  <li>
    ReLu (ouput input directly if posiive otherwise 0. Widely used in hidden layers)
  </li>
</ul>

Neurons are organized into layers. There are three main
<ul>
  <li>
    Input Layer
  </li>
  <li>
    Hidden layers
  </li>
  <li>
    Output layer
  </li>
</ul>

`Input layer` recieves an input in raw form. Each neuron in this layer represents a feature of input data
<br/>
`Hidden layer` are layers that transform the input into something the output layer can use
<br/>
`Output layer` is final layer that produces the output. The number of neurons in this layer depends on nature of task

#### How neural network works?
<ol>
  <li>
    Each node has its own linear regression model composed of
      <ul>
        <li>
          Input Layer
        </li>
        <li>
          Weight
        </li>
        <li>
          Bias (Each neuron has bias that allows the activation function to be shifted left or right, which helps the model fit the data better)
        </li>
      </ul>
  </li>
  <li>
    Once input layer is determined, weights are assigned. It helps deremine the importance of any given variable, with larger ones contributong more significantly to the output
  </li>
  <li>
    All input multiplied by their respective weights are then summed
  </li>
  <li>
    The sum output is passed through an activation function which determines the output
  </li>
  <li>
    Output of one node becomes input of next node. This process of passing data from one layer to next layer defines the neural network as feed forward neural network
  </li>
</ol>

## PyTorch


### Tensor
`Tensors` are fundamental concept in deep learning serving as a primary data structure for storing and manipulating data. It is a multi-dimensional array that generalizes scalars, vectors, and matrices to higher dimensions

It is a way to represenst complex data structures and are essential for performing mathematical operaiton in deep learning. In Pytorchm, almost everything is referred as tensor

In context of deep learning, tensors refers to the generalization of vectors and matrices to an arbitary number of dimensions. Another name for the same concept is *`multi-dimensional array`*

Types of tensors include


*   Scalar
*   Vector
*   Matrix
*   3D Tensor
*   ND Tensor



**`Scalar tensor`** are single numbers and also known as 0 dimensional tensor

In [7]:
scalar = torch.tensor(7) #scalar tensor
print(f"Scalar: {scalar}")
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Type: {type(scalar)}")

Scalar: 7
Dimension of scalar: 0
Type: <class 'torch.Tensor'>


We can retrieve the data inside a tensor as a python integer

In [8]:
print(f"Item inside the scalar: {scalar.item()}") # Here we get the value stored as a python integer
print(f"Type of item stored in the scalar: {type(scalar.item())}")

Item inside the scalar: 7
Type of item stored in the scalar: <class 'int'>


**`Vector`** are one dimensional array of numbers

In [9]:
vector = torch.tensor([7, 7]) #vector has magnitude and a direction
print(f"Vector: {vector}")  # you can calculate the number of dimension by counting the square
                            # brackets []
print(f"Dimension of vector: {vector.ndim}")
print(f"Shape of vector: {vector.shape}")

Vector: tensor([7, 7])
Dimension of vector: 1
Shape of vector: torch.Size([2])


**`Matrix`** are two-dimensional array of numbers

In [10]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]]) #matrix is usally indicated with capital name

print(f"Matrix: {MATRIX}")
print(f"Dimension of matrix: {MATRIX.ndim}")
print(f"Shape of matrix: {MATRIX.shape}")
print(f"Type of matrix: {type(MATRIX)}")
print(f"First item in the matrix: {MATRIX[0]}")

Matrix: tensor([[ 7,  8],
        [ 9, 10]])
Dimension of matrix: 2
Shape of matrix: torch.Size([2, 2])
Type of matrix: <class 'torch.Tensor'>
First item in the matrix: tensor([7, 8])


**3D Tensor** is a three-dimensional array of numbers, often used to
represent a sequence of matrices

In [11]:
 TENSOR = torch.tensor([[[1, 2],
                         [3, 4],
                         [4, 5]]]) # tensor are also named capital
print(f"Tensor: {TENSOR}")
print(f"Shape of tensor: {TENSOR.shape}")
print(f"Dimension of tensor: {TENSOR.ndim}")
print(f"Type of tensor: {type(TENSOR)}")
print(f"Second item in the tensor: {TENSOR[0]}")

Tensor: tensor([[[1, 2],
         [3, 4],
         [4, 5]]])
Shape of tensor: torch.Size([1, 3, 2])
Dimension of tensor: 3
Type of tensor: <class 'torch.Tensor'>
Second item in the tensor: tensor([[1, 2],
        [3, 4],
        [4, 5]])


**Random tensors** are tensors filled with random values. Random numbers are crucial in deep learning for various reasons

*   Weights in neural network are typically initialized with random values
*   Random tensors can be used to introduce randomness and variability in the input data during training
*   The way neural network learn is they start with tensors full of random numbers and then adjust those random number to better represent the data



***`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`***

In [12]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(f"Tensor with random values and of shape (3, 4): \n\n{random_tensor}")

Tensor with random values and of shape (3, 4): 

tensor([[0.6672, 0.1332, 0.8477, 0.5400],
        [0.7751, 0.2600, 0.5883, 0.7640],
        [0.3466, 0.2019, 0.6494, 0.5128]])


In [45]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, of color
                                                          # channels (R, G, B)
random_image_size_tensor

tensor([[[0.7789, 0.9671, 0.9627],
         [0.9973, 0.0995, 0.5866],
         [0.9299, 0.4142, 0.7746],
         ...,
         [0.7212, 0.3567, 0.0506],
         [0.4683, 0.7544, 0.8661],
         [0.9962, 0.1573, 0.9356]],

        [[0.1309, 0.3091, 0.3121],
         [0.1000, 0.6089, 0.5859],
         [0.3567, 0.7816, 0.6649],
         ...,
         [0.1116, 0.6984, 0.6725],
         [0.1077, 0.0357, 0.9666],
         [0.9041, 0.2112, 0.4902]],

        [[0.7164, 0.5593, 0.4399],
         [0.1770, 0.1366, 0.8591],
         [0.4599, 0.4374, 0.6637],
         ...,
         [0.3293, 0.8928, 0.1439],
         [0.6255, 0.5210, 0.1135],
         [0.3691, 0.4658, 0.5474]],

        ...,

        [[0.8911, 0.5221, 0.6324],
         [0.1247, 0.4185, 0.0520],
         [0.5082, 0.2870, 0.4402],
         ...,
         [0.6544, 0.6166, 0.6535],
         [0.6125, 0.9050, 0.7228],
         [0.4790, 0.4963, 0.1604]],

        [[0.0831, 0.0322, 0.0552],
         [0.1448, 0.1376, 0.6349],
         [0.

In [46]:
# we can create a tensor of zeros values
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# We can also create a tensor os specified shape containing only one
ones = torch.ones(size=(4, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
torch.arange(0 ,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
even_numbers = torch.arange(0, 10, 2)
even_numbers

tensor([0, 2, 4, 6, 8])

In pytorch we use **tensor_like** function

*   When you need to create new tensors that match the shape and data type of existing tensors, thus ensuring consistency
*   Make the code more readable and concise
*   Simplifies the process of creating tensors that share properties with an existing tensor



In [54]:
# creating tensors like
ten_zeros = torch.zeros_like(input=even_numbers)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Indexing tensors

We can index tensors with the same notation just as in NumPy and other python scientific libraries

**Vector Tensors**

In [22]:
tensor = torch.arange(0, 10)

print(f"Tensor: {tensor}")
print(f"\nFirst Element: {tensor[0]}")
print(f"\nLast Element: {tensor[-1]}")
print(f"\nFirst Two elements: {tensor[:2]}")

Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

First Element: 0

Last Element: 9

First Two elements at 1 index: tensor([0, 1])


**Matrix Tensors**

In [20]:
print(f"Tensor: {random_tensor}")
print(f"\nElement on 0 index: {random_tensor[0]}")
print(f"\nFirst Element: {random_tensor[0][0]}")
print(f"\nLast Element: {random_tensor[-1][-1]}")
print(f"\nFirst Two elements at 1 index: {random_tensor[1][:2]}")

Tensor: tensor([[0.6672, 0.1332, 0.8477, 0.5400],
        [0.7751, 0.2600, 0.5883, 0.7640],
        [0.3466, 0.2019, 0.6494, 0.5128]])

Element on 0 index: tensor([0.6672, 0.1332, 0.8477, 0.5400])

First Element: 0.6672316193580627

Last Element: 0.5127742886543274

First Two elements at 1 index: tensor([0.7751, 0.2600])


### Named tensors
***Named tensors*** are feature in PyToch that allows you to associate names with the dimensions of a tenor, making tensor opeartion more readable and less error prone. It also improves readability and makes debugging easy

In [36]:
tensor = torch.rand(2, 3, 3, names=('Red', 'Green', 'Blue'))
print(f"Tensor: {tensor}")
print(f"\nTensor name: {tensor.names}")

Tensor: tensor([[[0.4258, 0.9583, 0.6628],
         [0.5865, 0.0043, 0.2080],
         [0.9383, 0.1263, 0.2689]],

        [[0.0671, 0.0651, 0.5719],
         [0.2749, 0.6852, 0.7090],
         [0.5319, 0.3624, 0.5232]]], names=('Red', 'Green', 'Blue'))

Tensor name: ('Red', 'Green', 'Blue')


We can select a specific dimension using its name

In [30]:
red_color = tensor.select(dim='Red', index=0)
print(f"Red color data: {red_color}")

Red color data: tensor([[0.2436, 0.0957, 0.1743],
        [0.2378, 0.0855, 0.5250],
        [0.0725, 0.0408, 0.1775]], names=('Green', 'Blue'))


We can rename existing tensors

In [35]:
new_tensor = tensor.rename(Red='red_color', Green='green_color')
print(f"New Tensor: {new_tensor}")
print(f"\nNew names: {new_tensor.names}")

New Tensor: tensor([[[0.2436, 0.0957, 0.1743],
         [0.2378, 0.0855, 0.5250],
         [0.0725, 0.0408, 0.1775]],

        [[0.6060, 0.9309, 0.7031],
         [0.0628, 0.6746, 0.0414],
         [0.2047, 0.2586, 0.1226]]],
       names=('red_color', 'green_color', 'Blue'))

New names: ('red_color', 'green_color', 'Blue')


Performing some examples

In [44]:
red, green, blue =  3, 64, 64
images = torch.rand(red, green, blue, names=('red', 'green', 'blue'))

print(f"Images {images}")

red_mean = images.mean(dim='red', keepdim=True)
green_std = images.std(dim='green', keepdim=False)

print(f"\nRed color mean: {red_mean}")
print(f"\nGreen color mean: {green_std}")

Images tensor([[[0.0622, 0.1264, 0.7123,  ..., 0.7022, 0.5376, 0.0841],
         [0.6538, 0.0045, 0.6487,  ..., 0.4707, 0.3573, 0.8898],
         [0.6224, 0.1207, 0.6166,  ..., 0.2881, 0.8859, 0.8363],
         ...,
         [0.3276, 0.4432, 0.6523,  ..., 0.9133, 0.2721, 0.2487],
         [0.6604, 0.4026, 0.8583,  ..., 0.3986, 0.3913, 0.7750],
         [0.6729, 0.9702, 0.8605,  ..., 0.7345, 0.8964, 0.1710]],

        [[0.6086, 0.8549, 0.0965,  ..., 0.2895, 0.8981, 0.5714],
         [0.5560, 0.1346, 0.1417,  ..., 0.2531, 0.9660, 0.1326],
         [0.4762, 0.3648, 0.7717,  ..., 0.3214, 0.6674, 0.1684],
         ...,
         [0.7767, 0.2220, 0.1748,  ..., 0.5914, 0.1453, 0.6945],
         [0.7204, 0.9521, 0.3169,  ..., 0.1089, 0.5585, 0.0336],
         [0.7296, 0.8808, 0.2808,  ..., 0.1825, 0.5623, 0.1948]],

        [[0.9736, 0.8402, 0.8647,  ..., 0.5777, 0.4864, 0.8276],
         [0.6686, 0.5525, 0.2231,  ..., 0.4558, 0.5644, 0.8896],
         [0.7455, 0.5204, 0.2836,  ..., 0.6366, 0.8

### Tensor element attributes

Tensors have some important attributes like

*   **tensor.dtype** (returns the data type of the tensor's elements)
*   **tensor.device** (indicates the device on which the tensor is stored like CPU, GPU)
*   **tensor.numel()** (returns the total number of elements in the tensor)
*   **tensor.layout** (returns the layout of tensor)
*   **tensor.requires_grad** (indicates whehter gradient computation is required for the tensor?)





The **dtype** argument specifies the numerical data type that will be contained in the tensor. It specifies the possible value the tensor can hold and the number of bytes per value.
<br/>
Computation in neural network are typically executed with 32-bit floating-point precision. 64-bit does not improve accuracy in the model and will require more memory and computing time

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # data type of the tensor
                               device="cpu", # what devices is your tensor on
                               requires_grad=False) # want pytorch to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#always creates a copy
float_64_tensor = float_32_tensor.type(torch.float64) #float_32_tensor is not changed
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_32_tensor.dtype

torch.float32

### Tensor Arithmetics

**We can perform arthematic operations on the tensors**

In [ ]:
# manipulating tensors
# additions, subtraction, multiplication (element-wise), division, matrix multiplication

In [ ]:
ten = torch.tensor([1, 2, 3])
print(f"Tensor: {ten}")
print(f"Adding 10 to the tensor: {ten + 10}")
print(f"Multiplying 25 with the tensor: {ten * 25}")
print(f"Multiplying 10 with the tensor: {torch.mul(ten, 10)}")
print(f"Dividing the tensor by 2: {ten/ 2}")

Tensor: tensor([1, 2, 3])
Adding 10 to the tensor: tensor([11, 12, 13])
Multiplying 25 with the tensor: tensor([25, 50, 75])
Multiplying 10 with the tensor: tensor([10, 20, 30])
Dividing the tensor by 2: tensor([0.5000, 1.0000, 1.5000])


In [ ]:
# two main types of multiplication in deep learning
# 1) element wise multiplication
# 2) matrix multiplication (dot product) (most common operation in deep learning)

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor * tensor # element wise multiplication

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor) # matrix multiplication

tensor(14)

`tensor @ tensor` **@** is other way for matrix multiplication (not a recommended approach)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]

print(value)

tensor(12)
CPU times: user 2.66 ms, sys: 1.07 ms, total: 3.73 ms
Wall time: 13.9 ms


In [ ]:
%%time
torch.dot(tensor, tensor)

CPU times: user 1.01 ms, sys: 0 ns, total: 1.01 ms
Wall time: 1.02 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 1.01 ms


tensor(14)

There are two main rules that performing matrix multiplication needs to satisfy

1.   The inner dimension must match
*   (3, 2) @ (3, 2) will not work
*   (2, 3) @ (3, 2) will work
*   (3, 2) @ (2, 3) will work

2.   The resulting matrix has the shape of the outer dimension
*   (2, 3) @ (3, 2) will have shape (2, 2)
*   (3, 2) @ (2, 3) will have shape (3, 3)





In [3]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # error because inner dimension
                                # do not match

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) # no error

tensor([[0.2433, 1.2289],
        [0.0890, 0.5614]])

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)).shape

torch.Size([2, 2])

One of the most common errors in deep learning is shape error. To fix our tensor shape issues, we can manipulate the shape of one of our
tensors using a transpose

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2).T) # no error

tensor([[0.0636, 0.6495, 0.4846],
        [0.0420, 0.3916, 0.3926],
        [0.0702, 0.6126, 0.7372]])

### Tensor Aggregation

**finding min, max, mean, sum, etc**

In [4]:
tensor = torch.arange(0, 100)

In [5]:
print(f"\nTensor: {tensor}")
print(f"Minimum value: {tensor.min}")
print(f"Maximum value: {tensor.max}")


Tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
Minimum value: <built-in method min of Tensor object at 0x7a41fb2f6a20>
Maximum value: <built-in method max of Tensor object at 0x7a41fb2f6a20>


**mean doesn't work with int64 or long**

In [7]:
print(f"Mean: {torch.mean(tensor.type(torch.float32))}")
# converting to float32
print(f"Median: {tensor.median()}")
print(f"Sum: {torch.sum(tensor)}")

Mean: 49.5
Median: 49
Sum: 4950


#### Positional min max of tensors
In the context of tensors, finding positional min and max involves not only determining the minimum and maximum values but also identifying the position (*indices*) where these value occur.

In [16]:

print(f"Position of minimum value: {tensor.argmin()}")
# returns the index position where the minimum value occurs

print(f"Position of maximum value: {tensor.argmax()}")
# returns the index position where the minimum value occurs

Position of minimum value: 53
Position of maximum value: 7


In [9]:
tensor = torch.rand(8, 8)

In [10]:
print(f"Tensor: {tensor}")
print(f"Position of minimum value: {tensor.argmin()}")
print(f"Position of maximum value: {tensor.argmax()}")

Tensor: tensor([[9.1966e-01, 2.7856e-02, 8.5210e-01, 8.5290e-01, 2.8515e-01, 4.7567e-01,
         7.3274e-01, 9.8351e-01],
        [1.4489e-01, 3.4806e-01, 5.9828e-02, 2.3390e-01, 5.1137e-01, 9.0029e-01,
         4.7636e-01, 6.9137e-01],
        [8.3104e-02, 8.3162e-01, 5.2739e-01, 3.1169e-01, 4.1097e-01, 2.3216e-02,
         6.4255e-01, 4.5943e-01],
        [7.4951e-02, 5.2587e-01, 2.4780e-02, 4.1653e-01, 9.3602e-01, 9.1294e-01,
         4.1436e-02, 7.7510e-01],
        [8.0107e-01, 7.5273e-01, 8.5156e-01, 5.7133e-01, 5.0669e-01, 6.3028e-01,
         1.6166e-01, 5.3324e-03],
        [7.0224e-01, 4.9582e-01, 5.5058e-01, 4.7480e-01, 5.7500e-01, 3.1480e-01,
         9.0592e-01, 7.0695e-01],
        [6.0275e-03, 1.5420e-01, 5.2672e-01, 4.6139e-01, 7.6842e-01, 6.2776e-04,
         9.2860e-01, 9.4003e-01],
        [9.0865e-01, 1.2922e-01, 4.7545e-01, 3.4608e-01, 6.1136e-01, 9.1591e-01,
         5.7778e-01, 8.0731e-01]])
Position of minimum value: 53
Position of maximum value: 7


### Reshaping, Stacking, Qqueezing and Unsqueezing Tensors



*   **Reshaping** - reshapes an input tensor to a defined shape
*   **View** -  return a view of an input tensor of certain but keep the same memory as the originial tensor
*   **Stacking** - combine multiple tensors on top of each other
*   **Squeeze** -  remove all `1` dimensions from a tensor
*   **Unsqueeze** - add a `1` dimension to a target tensor
*   **Permute** - return a view of the input with dimensions permuted (swapped) in a certain way

In [17]:
tensor = torch.rand(3, 5)
tensor, tensor.shape

(tensor([[0.3823, 0.7687, 0.2623, 0.4473, 0.1350],
         [0.0723, 0.2757, 0.5578, 0.1750, 0.6667],
         [0.7786, 0.0263, 0.6258, 0.8889, 0.8857]]),
 torch.Size([3, 5]))

In [18]:
tensor_reshaped = tensor.reshape(1, 15)
tensor_reshaped, tensor_reshaped.shape

(tensor([[0.3823, 0.7687, 0.2623, 0.4473, 0.1350, 0.0723, 0.2757, 0.5578, 0.1750,
          0.6667, 0.7786, 0.0263, 0.6258, 0.8889, 0.8857]]),
 torch.Size([1, 15]))

In [ ]:
z = tensor.view(3, 5) #changing z changes tensor (because a view of tensor shares
                    # the same memory as original)
z, z.shape

(tensor([[0.1364, 0.2351, 0.1271, 0.8342, 0.5425],
         [0.7679, 0.2764, 0.1265, 0.2041, 0.3384],
         [0.8958, 0.1590, 0.2624, 0.5675, 0.2305]]),
 torch.Size([3, 5]))

In [ ]:
z[:, 0] = 5

In [ ]:
tensor

tensor([[5.0000, 0.2351, 0.1271, 0.8342, 0.5425],
        [5.0000, 0.2764, 0.1265, 0.2041, 0.3384],
        [5.0000, 0.1590, 0.2624, 0.5675, 0.2305]])

**Stacking** combines multiple tensors along a new dimension. This is useful for creating batches of data or combining ouputs from different models


In [ ]:
# stacks tensors on top of each other
x_stacked = torch.stack([tensor, tensor], dim=2)
x_stacked

tensor([[[5.0000, 5.0000],
         [0.2351, 0.2351],
         [0.1271, 0.1271],
         [0.8342, 0.8342],
         [0.5425, 0.5425]],

        [[5.0000, 5.0000],
         [0.2764, 0.2764],
         [0.1265, 0.1265],
         [0.2041, 0.2041],
         [0.3384, 0.3384]],

        [[5.0000, 5.0000],
         [0.1590, 0.1590],
         [0.2624, 0.2624],
         [0.5675, 0.5675],
         [0.2305, 0.2305]]])

**Squeezing** removes dimensions of size 1 from a tensor. This is useful for removing unnecessary dimensions, especially after operations like aggregations that can add extra dimensions.

In [23]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
print("Original Tensor with extra dimension:\n", tensor)
print("Original Tensor dimension:", tensor.ndim)

# Squeeze the tensor to remove dimensions of size 1
squeezed_tensor = tensor.squeeze()
print("\nSqueezed Tensor:\n", squeezed_tensor)
print("Squeezed Tensor dimension:", squeezed_tensor.ndim)


Original Tensor with extra dimension:
 tensor([[[1, 2, 3],
         [4, 5, 6]]])
Original Tensor dimension: 3

Squeezed Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Squeezed Tensor dimension: 2


**Unsqueezing** adds a dimension of size 1 to a tensor. This is useful when you need to add a batch dimension or channel dimension for specific operations or model requirements.

In [24]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:\n", tensor)
print("Original Tensor dimension:", tensor.ndim)

# Unsqueeze the tensor to add a new dimension at dim=0
unsqueezed_tensor = tensor.unsqueeze(dim=0)
print("Unsqueezed Tensor along dim=0:\n", unsqueezed_tensor)
print("Unsqueezed Tensor dimension:", unsqueezed_tensor.ndim)


Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Original Tensor dimension: 2
Unsqueezed Tensor along dim=0:
 tensor([[[1, 2, 3],
         [4, 5, 6]]])
Unsqueezed Tensor dimension: 3


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# commonly used for images
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # the 2nd index (3) is re-ordered to start

# re-orders the shape indexes

print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [ ]:
# numpy and pytorch
# numpy to pytorch (torch.from_numpy(ndarray))
# pytorch to numpy (torch.Tensor.numpy())

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #numpy default datatype is float64
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

In [2]:
#pytorch reproduceability
# ***`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`***

# To reduce randomness in neural networks and Pytorch comes the concept of a random seed

In [3]:
random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(f"Random tensor A: {random_A}")
print(f"Random tensor B: {random_B}")
print(random_A == random_B)

Random tensor A: tensor([[0.0482, 0.7124, 0.8801, 0.6303],
        [0.4352, 0.1096, 0.8976, 0.8997],
        [0.2484, 0.4821, 0.9280, 0.9965]])
Random tensor B: tensor([[0.5120, 0.8107, 0.0403, 0.4691],
        [0.2694, 0.5730, 0.2722, 0.0104],
        [0.5658, 0.4776, 0.8009, 0.8854]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
# lets make some random but reproduceable tensors

RANDOM_SEED = 42 # const that's why capitalized

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)

print(f"Random tensor C: {random_C}")
print(f"Random tensor D: {random_D}")
print(random_C == random_D)


Random tensor C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random tensor D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Read**
<br/>
https://pytorch.org/docs/stable/notes/randomness.html
<br/>
https://en.wikipedia.org/wiki/Random_seed

In [1]:
!nvidia-smi

Mon Aug  5 05:42:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# check for GPU access with Pytorch
torch.cuda.is_available()

True

In [5]:
torch.cuda.device_count()

1

In [6]:
# putting tensors and models on the GPU
# the reason we want our tensors/models on the GPU is because using a GPU results
# in faster calculation

In [ ]:
# create a tensor (on CPU)

tensor = torch.tensor([1, 2, 3], device= 'CPU')

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
second_point = points[1]
second_point.storage_offset()

2