In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction
`Deep learning` is a specialised form of deep learning that involves neural network with many deep layers. Neural networks are designed to mimic the human's brain ability to recognize patterns and intercept complex data such as iamge, sound, or text

### Difference b/w machine learning and deep learning

<ul>
    Machine learning is used for tabular or structured data
  <li>
    Machine learning requires feature engineering (select best relevant features)
  </li>
  <li>
    Simpler and easy to interpret
  </li>
  <li>
    Are computationally efficient and doesn't require high processing power
  </li>
</ul>

<ul>
    Deep learning works better for unstructured data like images, text, sound or video
  <li>
    Doesn't requires feature engineering
  </li>
  <li>
    Due to complexity and depth, they are difficult to understand and are referred as black box
  </li>
  <li>
    Works better with large amount of training data
  </li>
  <li>
    Requires substantional competitive power
  </li>
</ul>

### Neural Network
They are complex computational models that are inspired by human brain strucutre and function. It consist of following layers
<ul>
  <li>
    Artifical neurons or nodes
  </li>
  <li>
    Input layer
  </li>
  <li>
    One or more hidden layers
  </li>
  <li>
    Output layer
  </li>
</ul>

`Neurons` are fundamental units of neural network which
<ul>
  <li>
    Recieves an input
  </li>
  <li>
    Process the input
  </li>
  <li>
    Produces an output
  </li>
</ul>

Each neuron has its own linear regresion model that is used to predict output using weighted inputs

Each neuron has an activation function that introduces non-linear into the network, enabling it to learn and model complex problems. An `activation function` decides whether a neuron should be activated or not. This means that `it will decide whether the neuron's input to the network is important or not in the process of prediction using simpler mathematical operations.`
<ul>
  <li>
    Sigmoid (outputs between 0 and 1)
  </li>
  <li>
    Tanh (output between -1 and 1)
  </li>
  <li>
    ReLu (ouput input directly if posiive otherwise 0. Widely used in hidden layers)
  </li>
</ul>

Neurons are organized into layers. There are three main
<ul>
  <li>
    Input Layer
  </li>
  <li>
    Hidden layers
  </li>
  <li>
    Output layer
  </li>
</ul>

`Input layer` recieves an input in raw form. Each neuron in this layer represents a feature of input data
<br/>
`Hidden layer` are layers that transform the input into something the output layer can use
<br/>
`Output layer` is final layer that produces the output. The number of neurons in this layer depends on nature of task

#### How neural network works?
<ol>
  <li>
    Each node has its own linear regression model composed of
      <ul>
        <li>
          Input Layer
        </li>
        <li>
          Weight
        </li>
        <li>
          Bias (Each neuron has bias that allows the activation function to be shifted left or right, which helps the model fit the data better)
        </li>
      </ul>
  </li>
  <li>
    Once input layer is determined, weights are assigned. It helps deremine the importance of any given variable, with larger ones contributong more significantly to the output
  </li>
  <li>
    All input multiplied by their respective weights are then summed
  </li>
  <li>
    The sum output is passed through an activation function which determines the output
  </li>
  <li>
    Output of one node becomes input of next node. This process of passing data from one layer to next layer defines the neural network as feed forward neural network
  </li>
</ol>

## PyTorch


### Tensor
`Tensors` are fundamental concept in deep learningserving as a primary data structure for storing and manipulating data. It is a multi-dimensional array that generalizes scalars, vectors, and matrices to higher dimensions

It is a way to represenst complex data structures and are essential for performing mathematical operaiton in deep learning. In Pytorchm, almost everything is referred as tensor

Types of tensors include


*   Scalar
*   Vector
*   Matrix
*   3D Tensor
*   ND Tensor



**`Scalar tensor`** are single numbers and also known as 0 dimensional tensor

In [ ]:
scalar = torch.tensor(7) #scalar tensor
print(f"Scalar: {scalar}")
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Type: {type(scalar)}")

Scalar: 7
Dimension of scalar: 0
Type: <class 'torch.Tensor'>


We can retrieve the data inside a tensor as a python integer

In [ ]:
print(f"Item inside the scalar: {scalar.item()}") # Here we get the value stored as a python integer
print(f"Type of item stored in the scalar: {type(scalar.item())}")

Item inside the scalar: 7
Type of item stored in the scalar: <class 'int'>


**`Vector`** are one dimensional array of numbers

In [ ]:
vector = torch.tensor([7, 7]) #vector has magnitude and a direction
print(f"Vector: {vector}")  # you can calculate the number of dimension by counting the square
                            # brackets []
print(f"Dimension of vector: {vector.ndim}")
print(f"Shape of vector: {vector.shape}")

Vector: tensor([7, 7])
Dimension of vector: 1
Shape of vector: torch.Size([2])


**`Matrix`** are two-dimensional array of numbers

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]]) #matrix is usally indicated with capital name

print(f"Matrix: {MATRIX}")
print(f"Dimension of matrix: {MATRIX.ndim}")
print(f"Shape of matrix: {MATRIX.shape}")
print(f"Type of matrix: {type(MATRIX)}")
print(f"First item in the matrix: {MATRIX[0]}")

Matrix: tensor([[ 7,  8],
        [ 9, 10]])
Dimension of matrix: 2
Shape of matrix: torch.Size([2, 2])
Type of matrix: <class 'torch.Tensor'>
First item in the matrix: tensor([7, 8])


**3D Tensor** is a three-dimensional array of numbers, often used to
represent a sequence of matrices

In [ ]:
 TENSOR = torch.tensor([[[1, 2],
                         [3, 4],
                         [4, 5]]]) # tensor are also named capital
print(f"Tensor: {TENSOR}")
print(f"Shape of tensor: {TENSOR.shape}")
print(f"Dimension of tensor: {TENSOR.ndim}")
print(f"Type of tensor: {type(TENSOR)}")
print(f"Second item in the tensor: {TENSOR[0]}")

Tensor: tensor([[[1, 2],
         [3, 4],
         [4, 5]]])
Shape of tensor: torch.Size([1, 3, 2])
Dimension of tensor: 3
Type of tensor: <class 'torch.Tensor'>
Second item in the tensor: tensor([[1, 2],
        [3, 4],
        [4, 5]])


**Random tensors** are tensors filled with random values. Random numbers are crucial in deep learning for various reasons

*   Weights in neural network are typically initialized with random values
*   Random tensors can be used to introduce randomness and variability in the input data during training
*   The way neural network learn is they start with tensors full of random numbers and then adjust those random number to better represent the data



***`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`***

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(f"Tensor with random values and of shape (3, 4): \n\n{random_tensor}")

Tensor with random values and of shape (3, 4): 

tensor([[0.3550, 0.3605, 0.5246, 0.6180],
        [0.3620, 0.1204, 0.5568, 0.5691],
        [0.0963, 0.8359, 0.0884, 0.5536]])


In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, of color
                                                          # channels (R, G, B)
random_image_size_tensor

tensor([[[0.6083, 0.9721, 0.5859],
         [0.7717, 0.1164, 0.6863],
         [0.5714, 0.3780, 0.0363],
         ...,
         [0.5180, 0.0673, 0.9145],
         [0.5903, 0.5712, 0.1816],
         [0.8822, 0.6989, 0.9805]],

        [[0.0031, 0.3603, 0.8703],
         [0.8748, 0.8882, 0.0348],
         [0.4056, 0.4695, 0.4244],
         ...,
         [0.9328, 0.3702, 0.7721],
         [0.6633, 0.4525, 0.9984],
         [0.6792, 0.7905, 0.2288]],

        [[0.5939, 0.2008, 0.2115],
         [0.9025, 0.4215, 0.9674],
         [0.5754, 0.2539, 0.8895],
         ...,
         [0.1448, 0.0172, 0.1905],
         [0.1718, 0.3876, 0.2265],
         [0.3940, 0.2337, 0.6809]],

        ...,

        [[0.8155, 0.0582, 0.3077],
         [0.7600, 0.7464, 0.3036],
         [0.6078, 0.1981, 0.7122],
         ...,
         [0.3362, 0.5635, 0.1697],
         [0.9096, 0.9081, 0.1052],
         [0.2538, 0.4128, 0.3481]],

        [[0.8560, 0.9521, 0.6841],
         [0.4796, 0.3813, 0.4430],
         [0.

In [ ]:
# we can create a tensor of zeros values
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# We can also create a tensor os specified shape containing only one
ones = torch.ones(size=(4, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensors can be created using a `arange()`

In [ ]:
torch.arange(0 ,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
even_numbers = torch.arange(start=0, end=21, step=2)
even_numbers

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In pytorch we use **tensor_like** function

*   When you need to create new tensors that match the shape and data type of existing tensors, thus ensuring consistency
*   Make the code more readable and concise
*   Simplifies the process of creating tensors that share properties with an existing tensor



In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=even_numbers)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensors have some important attributes like

*   **tensor.dtype** (returns the data type of the tensor's elements)
*   **tensor.device** (indicates the device on which the tensor is stored like CPU, GPU)
*   **tensor.numel()** (returns the total number of elements in the tensor)
*   **tensor.layout** (returns the layout of tensor)
*   **tensor.requires_grad** (indicates whehter gradient computation is required for the tensor?)





In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # data type of the tensor
                               device="cpu", # what devices is your tensor on
                               requires_grad=False) # want pytorch to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#always creates a copy
float_64_tensor = float_32_tensor.type(torch.float64) #float_32_tensor is not changed
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_32_tensor.dtype

torch.float32

**We can perform arthematic operations on the tensors**

In [ ]:
# manipulating tensors
# additions, subtraction, multiplication (element-wise), division, matrix multiplication

In [ ]:
ten = torch.tensor([1, 2, 3])
print(f"Tensor: {ten}")
print(f"Adding 10 to the tensor: {ten + 10}")
print(f"Multiplying 25 with the tensor: {ten * 25}")
print(f"Multiplying 10 with the tensor: {torch.mul(ten, 10)}")
print(f"Dividing the tensor by 2: {ten/ 2}")

Tensor: tensor([1, 2, 3])
Adding 10 to the tensor: tensor([11, 12, 13])
Multiplying 25 with the tensor: tensor([25, 50, 75])
Multiplying 10 with the tensor: tensor([10, 20, 30])
Dividing the tensor by 2: tensor([0.5000, 1.0000, 1.5000])


In [13]:
# two main types of multiplication in deep learning
# 1) element wise multiplication
# 2) matrix multiplication (dot product) (most common operation in deep learning)

In [3]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [8]:
tensor * tensor # element wise multiplication

tensor([1, 4, 9])

In [9]:
torch.matmul(tensor, tensor) # matrix multiplication

tensor(14)

In [10]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]

print(value)

tensor(12)
CPU times: user 2.66 ms, sys: 1.07 ms, total: 3.73 ms
Wall time: 13.9 ms


In [11]:
%%time
torch.dot(tensor, tensor)

CPU times: user 1.01 ms, sys: 0 ns, total: 1.01 ms
Wall time: 1.02 ms


tensor(14)

In [12]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 1.01 ms


tensor(14)

In [ ]:
# There are two main rules that performing matrix multiplication needs to satisfy
# 1- The inner dimension must match
# (3, 2) @ (3, 2) will not work
# (2, 3) @ (3, 2) will work
# (3, 2) @ (2, 3) will work

In [16]:
tensor @ tensor # @ is other way for matrix multiplication (not a recommended approach)

tensor(14)

In [17]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [18]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) # no error

tensor([[0.2433, 1.2289],
        [0.0890, 0.5614]])

In [20]:
# 2) The resulting matrix has the shape of the outer dimension
# (2, 3) @ (3, 2) will have shape (2, 2)
# (3, 2) @ (2, 3) will have shape (3, 3)

In [21]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)).shape

torch.Size([2, 2])

In [22]:
# One of the most common errors in deep learning is shape error

In [23]:
# to fix our tensor shape issues, we can manipulate the shape of one of our
# tensors using a transpose

In [24]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2).T) # no error

tensor([[0.0636, 0.6495, 0.4846],
        [0.0420, 0.3916, 0.3926],
        [0.0702, 0.6126, 0.7372]])

In [26]:
# tensor aggregation
# finding min, max, mean, sum, etc

In [58]:
tensor = torch.arange(0, 100)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
tensor.min() # minimum

tensor(0)

In [41]:
torch.min(tensor) # another way to find minimum

tensor(0)

In [42]:
torch.max(tensor)

tensor(99)

In [46]:
torch.mean(tensor.type(torch.float32)) #mean doesn't work with int64 or long

tensor(49.5000)

In [48]:
torch.median(tensor)

tensor(49)

In [50]:
tensor.sum()

tensor(4950)

In [51]:
# positional min max of tensors

In [59]:
tensor.argmin() # returns the index position where the minimum value occurs

tensor(0)

In [60]:
tensor.argmax() # returns the index position where the maximum value occurs

tensor(99)

In [62]:
tensor = torch.rand(8, 8)

In [63]:
tensor.argmin()

tensor(41)

In [64]:
tensor.argmax()

tensor(44)

In [66]:
# reshaping, stacking, squeezing and unsqueezing tensors

In [67]:
# reshaping - reshapes an input tensor to a defined shape
# view -  return a view of an input tensor of certain but keep the same memory as the originial tensor
# stacking - combine multiple tensors on top of each other
# squeeze -  remove all `1` dimensions from a tensor
# unsqueeze - add a `1` dimension to a target tensor
# permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [70]:
tensor = torch.rand(3, 5)
tensor, tensor.shape

(tensor([[0.1364, 0.2351, 0.1271, 0.8342, 0.5425],
         [0.7679, 0.2764, 0.1265, 0.2041, 0.3384],
         [0.8958, 0.1590, 0.2624, 0.5675, 0.2305]]),
 torch.Size([3, 5]))

In [74]:
tensor_reshaped = tensor.reshape(1, 15)
tensor_reshaped, tensor_reshaped.shape

(tensor([[0.1364, 0.2351, 0.1271, 0.8342, 0.5425, 0.7679, 0.2764, 0.1265, 0.2041,
          0.3384, 0.8958, 0.1590, 0.2624, 0.5675, 0.2305]]),
 torch.Size([1, 15]))

In [78]:
z = tensor.view(3, 5) #changing z changes tensor (because a view of tensor shares
                    # the same memory as original)
z, z.shape

(tensor([[0.1364, 0.2351, 0.1271, 0.8342, 0.5425],
         [0.7679, 0.2764, 0.1265, 0.2041, 0.3384],
         [0.8958, 0.1590, 0.2624, 0.5675, 0.2305]]),
 torch.Size([3, 5]))

In [79]:
z[:, 0] = 5

In [80]:
tensor

tensor([[5.0000, 0.2351, 0.1271, 0.8342, 0.5425],
        [5.0000, 0.2764, 0.1265, 0.2041, 0.3384],
        [5.0000, 0.1590, 0.2624, 0.5675, 0.2305]])

In [83]:
# stacks tensors on top of each other
x_stacked = torch.stack([tensor, tensor], dim=2)
x_stacked

tensor([[[5.0000, 5.0000],
         [0.2351, 0.2351],
         [0.1271, 0.1271],
         [0.8342, 0.8342],
         [0.5425, 0.5425]],

        [[5.0000, 5.0000],
         [0.2764, 0.2764],
         [0.1265, 0.1265],
         [0.2041, 0.2041],
         [0.3384, 0.3384]],

        [[5.0000, 5.0000],
         [0.1590, 0.1590],
         [0.2624, 0.2624],
         [0.5675, 0.5675],
         [0.2305, 0.2305]]])

In [89]:
# squeez remove all single dimensions from a target tensor
tensor[:, 0] = 1
tensor, tensor.shape

(tensor([[1.0000, 0.2351, 0.1271, 0.8342, 0.5425],
         [1.0000, 0.2764, 0.1265, 0.2041, 0.3384],
         [1.0000, 0.1590, 0.2624, 0.5675, 0.2305]]),
 torch.Size([3, 5]))

In [90]:
tensor.squeeze(), tensor.squeeze().shape

(tensor([[1.0000, 0.2351, 0.1271, 0.8342, 0.5425],
         [1.0000, 0.2764, 0.1265, 0.2041, 0.3384],
         [1.0000, 0.1590, 0.2624, 0.5675, 0.2305]]),
 torch.Size([3, 5]))

In [93]:
tensor.unsqueeze(dim=0), tensor.unsqueeze(dim=0).shape

(tensor([[[1.0000, 0.2351, 0.1271, 0.8342, 0.5425],
          [1.0000, 0.2764, 0.1265, 0.2041, 0.3384],
          [1.0000, 0.1590, 0.2624, 0.5675, 0.2305]]]),
 torch.Size([1, 3, 5]))

In [96]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# commonly used for images
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # the 2nd index (3) is re-ordered to start

# re-orders the shape indexes

print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [97]:
# numpy and pytorch
# numpy to pytorch (torch.from_numpy(ndarray))
# pytorch to numpy (torch.Tensor.numpy())

In [98]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #numpy default datatype is float64
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [99]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

In [100]:
#pytorch reproduceability